name: Java CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd dmail
          mvn clean package

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dmail-war
          path: dmail/target/dmail.war
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dmail-war
          path: ${{ github.workspace }}/dmail/target/

      - name: Deploy to Tomcat via Manager
        run: curl -T "${{ github.workspace }}/dmail/target/dmail.war" --user "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASS }}" "https://api.hriday.tech/manager/text/deploy?path=/dmail&update=true"


